# -*- coding: utf-8 -*-
VOn = ["Dej si do pusy kostku ledu a udělej partnerce krátký orální sex", "Polož svoji partnerku na stůl. Odstraň její kalhotky s cesty, při tom si s ním hraj aby byl pěkně tvrdý a pak ho tam partnerce třikrát zasuň. Po třetím zasunutí úkol ukonči.", "Ohni svoji partnerku přes stůl a začni ji orálně dráždit. Přestaň v té chvíly, kdy ti stoupne."]
ROn = ["zavři oči a poslepu poznávej obrysy jejího těla.", "Pusťte si na chvíli lesbické porno. Schválně co to s kým udělá", "Minutu předstírej roli opačného pohlaví při sexu"]
IOn = ["Napiiš na papír 7 poloh na 7 dní v týdnu, které bys chtěl každý den vyzkoušet.", "Jak říkáš svému penisu?", "Ukaž svojí partnerce jaké máš na sobě spodní prádlo. Pokud jsi naostro, tím líp pro ni. :-) "]
VOna = ["Vášnivě líbej kořen varlat svého muže.", "Vlož partnerův penis mezi ňadra a jemě mu ho namasíruj.", "Lízej svému partnerovy bradavky."]
ROna = ["Předveď 3 gesta, kterými ukážeš partnerovi, že ho chceš.", "Nech partnera, aby si na chvíli sáhnul do tovjí lasturky.", "Na okamžki ukaž partnerovy nahá prsa (20 s).", "Začni svlékat svého partnera ústy. Musíš ho svléct celého bez použití rukou i nohou.", "Udělej si cucflek an místě které uvidí jen tvůj partner."]
IOna = ["Zažila jsi někdy anální sex? Líbilo se ti to?", "Předveď partnerovi, jak se umývá kočka.", "Máš ráda mazlení? Vyjmenuj 3 varinaty mazlení."]
On = ["Potěšte partnerku. Složte pro parnternku krátkou erotickou báseň opěvující její vnady nebo pro ni napiště erotickou povídku.", "Věnujte partnerce dárek v podobě erotických kalhotek a dírou v rozkroku. Vyzkoušejte si jaké to je, když se při sexu nemusíte zdržovat svlékáním spodního prádla.", "Připravte a donest jeden večer partnerce do postele jijí oblibenou pochoutku. Krmte ji nejprve lžičkou, potom prsty a nakonec ústy."]
Ona = ["Uspořádejte pro partnera erotické promítání. Předem sežeňtem a vyberte film s tématem,  které vašeho partnera nejvíc vzrušuje a večer mu ho pusťtě. Dokážete se dodívat do konce?", "Připravte pro partnera k večeři jeho oblíbené jídlo. Svlékněte se a na nahé tělo si oblečte pouze kuchyňskou zástěru. Vaření může začít."]
